### PR TITLE
Dropdown select

### PR DESCRIPTION
**Pull request by abrande**
Added Product Dropdown to Sign Up page:
Kapture 2020-03-11 at 12 43 19

UI Updates: 
Screen Shot 2020-03-12 at 2 25 16 PM

### CODE REVIEW

**Comment by nicko-winner** [comment]
UX question: Just wondering why put the field in a popover vs adding the dropdown inline with other form elements?

**Comment by explorigin** [comment]
The UI feels a bit weird here. Should we just use a drop-down instead of putting it in a popup (with 2 headers)?

**Comment by abrande** [comment]
I was using a component I had previously set up for the dropdown req we once had, I can change it now - I agree with both of you.

**Comment by nicko-winner** [comment]
UX thoughts:

The check box seems like it is kind of floating out there. key value pairs in helix tend to look like that if they only have one item in them. You might not need the separator between (HR/Border bottom) to separate the rbu checkbox from address. You might not need HR's in general, the headings do a pretty good job of splitting up the form sections, but if you do use them, consistency might help. There is a HR missing between "Account Product" and "Customer Information". "Address" could maybe be a smaller heading if it is under "Customer information" in the visual hierarchy.

**Pull request merged**
