### PR TITLE
Add an OK button to the modal

### PR DESCRIPTION
**Pull request by explorigin**
https://soundcloud.com/monstercat/tokyo-machine-okay

### CODE REVIEW

**Comment by usethecodeluke** [comment]
> https://soundcloud.com/monstercat/tokyo-machine-okay

Linking to random dubstep should be a requirement for PRs for now on.

**Comment by usethecodeluke** [comment]
Can we have a screengrab?

**Comment by explorigin** [comment]
Oooo, I originally based this off of Sophies branch and then rebased on master and it's broken. I needs Sophie's code. One sec.

**Comment by explorigin** [comment]
image

**Pull request merged**
